version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: wahlzeit
      POSTGRES_USER: wahlzeit
      POSTGRES_PASSWORD: wahlzeit
    ports:
      - 5432:5432
    networks:
      - backend
    # Uncomment for persistence independent of container
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8090:8080
    networks:
      - backend

  backend:
    image: wahlzeit
    build:
      context: .
    environment:
      WAHLZEIT_DB_HOST: "db"
    ports:
      - 8081:8080
    networks:
      - backend

  frontend:
    restart: always
    image: nginx:1.17.1-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ui/dist:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
